export const schoolData = {
  model: 'dashboard',
  data: [
    {
      level0: [
        {
          perform: [
            {
              nusantara: [
                {
                  summary: [
                    {
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                  ],
                  mapping: [
                    {
                      area: 'Jakarta',
                      lat: '-6.173258',
                      long: '106.824821',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Adaro',
                      lat: '-6.233082',
                      long: '106.833099',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Balikpapan',
                      lat: '-1.148889',
                      long: '116.903100',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Lampung',
                      lat: '-4.820391',
                      long: '105.077437',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Banjarmasin',
                      lat: '-3.316571',
                      long: '114.590582',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Batu Kajang',
                      lat: '-1.833232',
                      long: '115.917473',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Bontang',
                      lat: '0.135941',
                      long: '117.493397',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Ujung Pandang',
                      lat: '-5.140361',
                      long: '119.413272',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Medan',
                      lat: '3.586371',
                      long: '98.674991',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Palembang',
                      lat: '-2.987800',
                      long: '104.761788',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Pekanbaru',
                      lat: '0.527625',
                      long: '101.448837',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Samarinda',
                      lat: '-0.502183',
                      long: '117.153763',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Sangatta',
                      lat: '0.739284',
                      long: '117.386559',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Semarang',
                      lat: '-6.972037',
                      long: '110.427257',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Sorong',
                      lat: '-0.879560',
                      long: '131.261000',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Surabaya',
                      lat: '-7.241632',
                      long: '112.741204',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Tanjung Redeb',
                      lat: '2.143752',
                      long: '117.481963',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Tanjung Enim',
                      lat: '-3.761343',
                      long: '103.766167',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: '​Damai',
                      lat: '',
                      long: '',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Timika',
                      lat: '-4.542975',
                      long: '136.882096',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Jayapura',
                      lat: '-2.532956',
                      long: '140.715579',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                    {
                      area: 'Jakarta',
                      lat: '-6.163990',
                      long: '106.838254',
                      full: '0',
                      available_part: '0',
                      available: '0',
                      no_ar: '0',
                      ar: '0',
                      no_transaction: '0',
                    },
                  ],
                },
              ],
            },
            { graduate: [{ target: '0', achievment: '0', total_graduate: '0' }] },
            { student: [{ reguler: '0', non_reguler: '0', total_student: '0' }] },
            { sales: [{ target: '0', achivement: '0', achivement_ar: '0', top_customer: '0' }] },
          ],
        },
      ],
    },
    {
      kipl: [
        {
          pre: [
            { demand: [{ customer: '0', project: '0' }] },
            {
              project: [{ project: '0', amount: '0', customer: '0', ration: '0', win_ratio: '0' }],
            },
            {
              quotation: [
                {
                  expired: '0',
                  close: '0',
                  done: '0',
                  cancel: '0',
                  amount_expired: '0',
                  amount_close: '0',
                  amount_done: '0',
                  amount_cancel: '0',
                  total: '0',
                },
              ],
            },
          ],
          execution: [
            {
              po: 'project',
              data: [{ sponsor_fee: '0', training_fee: '0', konsultasi: '0', total_po: '0' }],
            },
            { po: 'pembayaran', data: [{ cash_payment: '0', payment1: '0', payment2: '0' }] },
            {
              po: 'event',
              data: [{ event: '0', event_amount: '0', event_status: [{ paid: '0', unpaid: '0' }] }],
            },
            { event: [{ close: '0', open: '0' }] },
            { reporting: [{ close: '0' }] },
            { bast: [{ open: '0' }] },
            { invoice: [{ open_billing: '0', close_billing: '0' }] },
            { ar_perform: [{ billing: '0', invoice: '0' }] },
          ],
          output: [
            {
              sales_performence: [
                { target: '0', achievment: '0', amount: '0', ar: '0', top_customer: '0' },
              ],
            },
            {
              cust_coverage: [
                {
                  ahemce: '0',
                  non_ahemce: '0',
                  new_customer_target: '0',
                },
              ],
            },
            { non_reguler_student: [{ student: '0' }] },
            { alumni: [{ serapan: '0' }] },
          ],
        },
      ],
    },
    {
      akademik: [
        {
          pre: [{ rencana_pembelajaran: [{ classroom: '0', student: '0' }] }],
          execution: [
            { siswa: [{ reguler: '0', non_reguler: '0', total: '0' }] },
            {
              kalendar_akademik: [
                {
                  bintalsik: [
                    { batch: '57', classroom: 'REG-90-XXX', total: '0' },
                    { batch: '2', classroom: 'REG-75-XXX', total: '0' },
                    { batch: '43', classroom: 'REG-56-XXX', total: '0' },
                    { batch: '76', classroom: 'REG-81-XXX', total: '0' },
                    { batch: '11', classroom: 'REG-31-XXX', total: '0' },
                  ],
                  in_class: [
                    { batch: '57', classroom: 'REG-90-XXX', total: '0' },
                    { batch: '2', classroom: 'REG-75-XXX', total: '0' },
                    { batch: '43', classroom: 'REG-56-XXX', total: '0' },
                    { batch: '76', classroom: 'REG-81-XXX', total: '0' },
                    { batch: '11', classroom: 'REG-31-XXX', total: '0' },
                  ],
                  ojt: [
                    { batch: '57', classroom: 'REG-90-XXX', total: '0' },
                    { batch: '2', classroom: 'REG-75-XXX', total: '0' },
                    { batch: '43', classroom: 'REG-56-XXX', total: '0' },
                    { batch: '76', classroom: 'REG-81-XXX', total: '0' },
                    { batch: '11', classroom: 'REG-31-XXX', total: '0' },
                  ],
                  lulus: [
                    { batch: '57', classroom: 'REG-90-XXX', total: '0' },
                    { batch: '2', classroom: 'REG-75-XXX', total: '0' },
                    { batch: '43', classroom: 'REG-56-XXX', total: '0' },
                    { batch: '76', classroom: 'REG-81-XXX', total: '0' },
                    { batch: '11', classroom: 'REG-31-XXX', total: '0' },
                  ],
                },
              ],
            },
          ],
          output: [
            {
              jumlah_alumni: [{ total: '0', non_reguler: '0', reguler: '0', csr: '0' }],
              grafik_alumni: [
                { year: '2023', month: '01', alumni: '0' },
                { year: '2023', month: '02', alumni: '0' },
                { year: '2023', month: '03', alumni: '0' },
                { year: '2023', month: '04', alumni: '0' },
                { year: '2023', month: '05', alumni: '0' },
                { year: '2023', month: '06', alumni: '0' },
                { year: '2023', month: '07', alumni: '0' },
                { year: '2023', month: '08', alumni: '0' },
                { year: '2023', month: '09', alumni: '0' },
                { year: '2023', month: '10', alumni: '0' },
                { year: '2023', month: '11', alumni: '0' },
                { year: '2023', month: '12', alumni: '0' },
              ],
            },
            { presentase: '0' },
          ],
        },
      ],
    },
  ],
};
