export const stocks = [
  { productName: 'ProductA', sum: 10 },
  { productName: 'ProductB', sum: 5 },
  { productName: 'ProductA', sum: 15 },
  { productName: 'ProductC', sum: 8 },
  { productName: 'ProductB', sum: 3 },
  { productName: 'ProductA', sum: 5 },
  { productName: 'ProductA', sum: 10 },
  { productName: 'ProductB', sum: 5 },
  { productName: 'ProductA', sum: 15 },
  { productName: 'ProductC', sum: 8 },
  { productName: 'ProductB', sum: 3 },
  { productName: 'ProductA', sum: 5 },
  { productName: 'ProductA', sum: 10 },
  { productName: 'ProductB', sum: 5 },
  { productName: 'ProductA', sum: 15 },
  { productName: 'ProductC', sum: 8 },
  { productName: 'ProductB', sum: 3 },
  { productName: 'ProductA', sum: 5 },
  { productName: 'ProductA', sum: 10 },
  { productName: 'ProductB', sum: 5 },
];
