export const variants = [
  { productName: 'ProductA', total: 10 },
  { productName: 'ProductB', total: 5 },
  { productName: 'ProductA', total: 15 },
  { productName: 'ProductC', total: 8 },
  { productName: 'ProductB', total: 3 },
  { productName: 'ProductA', total: 5 },
  { productName: 'ProductA', total: 10 },
  { productName: 'ProductB', total: 5 },
  { productName: 'ProductA', total: 15 },
  { productName: 'ProductC', total: 8 },
  { productName: 'ProductB', total: 3 },
  { productName: 'ProductA', total: 5 },
  { productName: 'ProductA', total: 10 },
  { productName: 'ProductB', total: 5 },
  { productName: 'ProductA', total: 15 },
  { productName: 'ProductC', total: 8 },
  { productName: 'ProductB', total: 3 },
  { productName: 'ProductA', total: 5 },
  { productName: 'ProductA', total: 10 },
  { productName: 'ProductB', total: 5 },
];
