apiVersion: apps/v1
kind: Deployment
metadata:
 name: icx-web-dashboard
 namespace: production
 labels:
   app: icx-web-dashboard
spec:
 replicas: 1
 selector:
   matchLabels:
     app: icx-web-dashboard
 template:
   metadata:
     labels:
       app: icx-web-dashboard
   spec:
     serviceAccountName: icx-prod-user
     serviceAccount: icx-prod-user
     containers:
       - name: icx-web-dashboard
         image: icx-web-dashboard-image
         imagePullPolicy: Always
         envFrom:
            - secretRef:
                name: icx-web-dashboard-secret
         volumeMounts:
            - name: tz
              mountPath: /etc/localtime
              subPath: Jakarta
     volumes:
       - name: tz
         configMap:
            name: tz
---
apiVersion: v1
kind: Service
metadata:
  name: icx-web-dashboard-service
  namespace: production
  labels:
    app: icx-web-dashboard
spec:
  ports:
    - port: 443
      targetPort: 5173
  selector:
    app: icx-web-dashboard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icx-web-dashboard-ingress
  namespace: production
  labels:
    app: icx-web-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: 108.136.34.127
    nginx.ingress.kubernetes.io/rewrite-target: /
status:
  loadBalancer:
    ingress:
      - ip: 34.101.225.199
spec:
  rules:
    - host: dashboard.icx.id
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service: 
                name: icx-web-dashboard-service
                port:
                  number: 5173