apiVersion: apps/v1
kind: Deployment
metadata:
  name: ybkut-web-dashboard
  namespace: production
  labels:
    app: ybkut-web-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ybkut-web-dashboard
  template:
    metadata:
      labels:
        app: ybkut-web-dashboard
    spec:
      serviceAccountName: ybkut-prod-user
      serviceAccount: ybkut-prod-user
      containers:
        - name: ybkut-web-dashboard
          image: ybkut-web-dashboard-image
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: ybkut-web-dashboard-secret
          volumeMounts:
            - name: tz
              mountPath: /etc/localtime
              subPath: Jakarta
      volumes:
        - name: tz
          configMap:
            name: tz
---
apiVersion: v1
kind: Service
metadata:
  name: ybkut-web-dashboard-service
  namespace: production
  labels:
    app: ybkut-web-dashboard
spec:
  ports:
    - port: 443
      targetPort: 5173
  selector:
    app: ybkut-web-dashboard

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ybkut-web-dashboard-ingress
  namespace: production
  labels:
    app: ybkut-web-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: 108.136.34.127
    nginx.ingress.kubernetes.io/rewrite-target: /
status:
  loadBalancer:
    ingress:
      - ip: 34.101.225.199
spec:
  rules:
    - host: dashboard.ybkut.id
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: ybkut-web-dashboard-service
                port:
                  number: 5173
